baseURL = 'https://snapsync.paul-nameless.com/'
languageCode = 'en-us'
title = 'SnapSync'
theme = 'PaperMod'
canonifyURLs = true

[[menu.main]]
identifier = "help-page"
name = "Help"
url = "/help/"
weight = 1

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 10

[params]
hideFooter = false

[markup.goldmark.parser.attribute]
block = true
title = true
