baseURL = 'https://snapsync.paul-nameless.com/'
languageCode = 'en-us'
title = 'SnapSync'
theme = 'PaperMod'
canonifyURLs = true

[[menu.main]]
identifier = "help"
name = "Help"
url = "/help/"
weight = 1

# [[menu.main]]
# identifier = "contact"
# name = "Contact"
# url = "/contact/"
# weight = 10

[params]
hideFooter = false
ShowToc = true

[markup.goldmark.parser.attribute]
block = true
title = true
